version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: "./Dockerfile"
    command: python  /code/manage.py runserver 0.0.0.0:8002
    networks:
      - books_network
    volumes:
      - .:/code
    ports:
      - 8002:8002
    depends_on:
      - db
    env_file:
      - ./envs/.env
    environment:
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5432"

  db:
    image: library/postgres:14-alpine
    networks:
      - books_network
    volumes:
      -  postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

networks:
  books_network:
    driver: bridge


volumes:
  postgres_data:
