version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: "./Dockerfile"
    command: python  /code/manage.py runserver 0.0.0.0:8002
    networks:
      - books_network
    volumes:
      - .:/code
    ports:
      - 8002:8002
    depends_on:
      - db
    env_file:
      - ./envs/.env


  db:
    image: library/postgres:14-alpine
    networks:
      - books_network
    volumes:
      -  postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.db

networks:
  books_network:
    driver: bridge


volumes:
  postgres_data:
