# Generated by Django 4.0.1 on 2022-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('publishedDate', models.IntegerField()),
                ('ISBN_13', models.CharField(max_length=13)),
                ('pageCount', models.IntegerField()),
                ('canonicalVolumeLink', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=5)),
            ],
        ),
    ]
