# Generated by Django 4.0.1 on 2022-02-04 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn_10_alter_book_isbn_13_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(-3000, message='Impossible year'), django.core.validators.MaxValueValidator(2023, message='Impossible year')]),
        ),
    ]
