# Generated by Django 4.0.1 on 2022-02-04 16:01

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn_10_alter_book_isbn_13_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishedDate',
            new_name='publisheddate',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=20, validators=[books.validators.validate_not_numeric]),
        ),
    ]
