# Generated by Django 4.0.1 on 2022-02-07 14:23

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_authors_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[books.validators.validate_is_in_db]),
        ),
    ]
